### PR TITLE
Update a_star_algorithm.dart

### PR DESCRIPTION
**Pull request by Horned-Nonsense**
This allows us to move diagonally directly and makes the algorithm more versatile and also reduces the number of iterations. Exmpl grid:

XOOXE
XXOOX
XOOXX
XOXXO
SXOOX

Where: S - start, E - end, X - barrier, O - free space

### CODE REVIEW

**Comment by RafaelBarbosatec** [comment]
Hi @Horned-Nonsense !
Thanks so much for contributing!
Some times we want not diagonal movement. Why did you remove withDiagonal param?

**Comment by Horned-Nonsense** [comment]
Hello @RafaelBarbosatec.  Perhaps I was a little hasty in deleting it. After submitting the PR, I thought that not having diagonal transitions makes sense, for example if it's an obstacle in the game like a diagonal wall, so I could leave the diagonal clearance check.
But if we consider the algorithm abstractly, then the possibility of diagonal moves should be preserved without taking into account the walls in the neighborhood.

**Comment by Horned-Nonsense** [comment]
@RafaelBarbosatec I return it back.

**Comment by RafaelBarbosatec** [comment]
LGTM! Thanks for contributing!

**Pull request merged**
